### ISSUE TITLE
Missing geometry after merge

### ISSUE THREAD

**Issue by 321C4** [321C4/skyislandsvr.com#4]
Need to go through the code on MossMarch and OverWater scenes, to fix missing geometry.

**Comment by 321C4** [comment]
Issue is mostly fixed. I rebuilt the scenes that needed fixing. Some geometry in Over Water is still distorted, but it's alright for now.

**Comment by cvan** [comment]
oh sorry about that. what was the issue?

**Comment by 321C4** [comment]
Not sure -- it's like some geometry turned inside-out. Odd thing is- the order of the entities in the code seems to determine what gets crumpled.
